apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment2
  namespace: jenkins
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask2
  strategy:
    rollingUpdate: 
      maxSurge: 25% 
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: flask2
    spec:
      containers:
      - name: flask-appv2
        image: noveedwork/activity4:appv2
        ports:
        - containerPort: 5500